### ISSUE TITLE
File Upload issue

### ISSUE THREAD

**Issue by mjwebhacks** [FayasNoushad/GoFile-Bot#20]
Sometimes file are getting downloaded on the server but when it starts to upload on gofile.io it throughs the below error.

pyrogram.errors.exceptions.bad_request_400.MessageNotModified: Telegram says: [400 MESSAGE_NOT_MODIFIED] - The message was not modified because you tried to edit it using the same content (caused by "messages.EditMessage")

**Comment by FayasNoushad** [comment]
can you give the whole error including line number

**Comment by mjwebhacks** [comment]
check out the Heroku
[mjgofile-logs-1651637696934.txt](https://github.com/FayasNoushad/GoFile-Bot/files/8617846/mjgofile-logs-1651637696934.txt)
 log file

**Comment by mjwebhacks** [comment]
For some video files it happens I tried 2-3 times to upload but getting same error.
