### ISSUE TITLE
[BUG] With new code Uploading is failing

### ISSUE THREAD

**Issue by mjwebhacks** [FayasNoushad/GoFile-Bot#23]
I tried to upload a 1Gb file from bot to gofile but the Heroku server is getting crashed it consumes a high amount of RAM and the server gets crashed check the log file. I think it happens due to editing the message it takes too much time to download and upload as compared to the previous version.

[mjgofile-logs-1651641327378.txt](https://github.com/FayasNoushad/GoFile-Bot/files/8618015/mjgofile-logs-1651641327378.txt)

**Comment by FayasNoushad** [comment]
Fixed on #24
