### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fermani10** [FayasNoushad/GoFile-Bot#31]
![image](https://user-images.githubusercontent.com/31140793/167298722-7c92459c-9102-493d-b2fe-e537c0132712.png)
Hello, I don't know why all the bots that I want to use for gofile fail me. One tells me directlink the error and this tells me server... is it something from the Api?

**Comment by FayasNoushad** [comment]
Logs please

**Comment by FayasNoushad** [comment]
Fixed
