### ISSUE TITLE
Few others issues identified

### ISSUE THREAD

**Issue by PlatFlat** [FayasNoushad/GoFile-Bot#35]
### **Issue 1:** 

When remote upload:
```
/upload http://ipv4.download.thinkbroadband.com/5MB.zip
``` 

**Bot Return Msg:** 
> name 'requests' is not defined

Might need to define an "import requests" 

### **Issue 2:**

When remote upload:
```
/upload http://ipv4.download.thinkbroadband.com/5MB.zip
``` 

**Bot Return Msg:** 
`name 'name' is not defined`

main.py - Line 90: "with open(name, "wb") as file"

### **Issue 3:**

When Issue 1 & 2 is fixed,

**Bot Return Msg:** 
`API Error (Not Vaild JSON Data Received)`

I think it have to do with gofile.py, might not have receive the correct response although logs indicate the download link/page.

Logs indicates:

> [info] {"status":"ok","data":{"guestToken":"grUiVlrJ2Z44pPCmY3B4c5p4EmNEnY2u","downloadPage":"https://gofile.io/d/wkpU1F","code":"wkpU1F","parentFolder":"fd8caac3-1e6b-415b-958f-f7ec95158c28","fileId":"1e2893ff-5673-4ada-b189-37aa21e9efd9","fileName":"5MB.zip","md5":"b3215c06647bc550406a9c8ccc378756"}}

### **Issue 4:**

Unable to upload normal file. Stuck at processing. 

```
/upload -attached file-
``` 

**Bot Return Msg:** 
`Processing...`

Logs indicates: 

>  'NoneType' object has no attribute 'replace'
> File "/workspace/main.py", line 58, in filter
> [info] text = update.text.replace("\n", " ")
> [info] ^^^^^^^^^^^^^^^^^^^
> [info] AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by FayasNoushad** [comment]
Fixed
